// Quelldaten der Stadion-Datenbank (Saison 2026/27, Top-5-Ligen).
// `npm run stadiums` geokodiert diese Liste über OpenStreetMap und schreibt src/data/stadiums.json.
//
// Felder: Liga, Vereinsname, Stadion, Stadt, Land (ISO), Geokodier-Suchbegriff, Aliasnamen.
// Suchbegriff leer => Stadionname wird gesucht. Aliasnamen helfen beim Abgleich mit den
// Vereinsnamen der verschiedenen Datenquellen (football-data.org, OpenLigaDB, openfootball …).

import type { LeagueCode } from '../src/shared/types.ts'

export type StadiumSource = [
  league: LeagueCode,
  team: string,
  stadium: string,
  city: string,
  country: string,
  query: string,
  aliases: string[],
]

export const STADIUM_SOURCE: StadiumSource[] = [
  // ---------- Bundesliga ----------
  ['BL1', 'FC Bayern München', 'Allianz Arena', 'München', 'de', '', ['Bayern Munich', 'Bayern München']],
  ['BL1', 'Borussia Dortmund', 'Signal Iduna Park', 'Dortmund', 'de', '', ['Dortmund']],
  ['BL1', 'Bayer 04 Leverkusen', 'BayArena', 'Leverkusen', 'de', '', ['Leverkusen']],
  ['BL1', 'RB Leipzig', 'Red Bull Arena', 'Leipzig', 'de', '', ['RasenBallsport Leipzig']],
  ['BL1', 'VfB Stuttgart', 'MHPArena', 'Stuttgart', 'de', '', []],
  ['BL1', 'Eintracht Frankfurt', 'Deutsche Bank Park', 'Frankfurt am Main', 'de', '', []],
  ['BL1', 'SC Freiburg', 'Europa-Park Stadion', 'Freiburg im Breisgau', 'de', '', ['Sport-Club Freiburg']],
  ['BL1', 'Borussia Mönchengladbach', 'Borussia-Park', 'Mönchengladbach', 'de', '', ["M'gladbach", 'Gladbach']],
  ['BL1', '1. FSV Mainz 05', 'MEWA ARENA', 'Mainz', 'de', 'Mewa Arena', ['Mainz 05', 'Mainz']],
  ['BL1', 'FC Augsburg', 'WWK ARENA', 'Augsburg', 'de', 'WWK Arena', ['Augsburg']],
  ['BL1', 'SV Werder Bremen', 'Weserstadion', 'Bremen', 'de', '', ['Werder Bremen']],
  ['BL1', '1. FC Union Berlin', 'Stadion An der Alten Försterei', 'Berlin', 'de', '', ['Union Berlin']],
  ['BL1', 'TSG Hoffenheim', 'PreZero Arena', 'Sinsheim', 'de', '', ['TSG 1899 Hoffenheim', 'Hoffenheim']],
  ['BL1', '1. FC Köln', 'RheinEnergieSTADION', 'Köln', 'de', 'RheinEnergieStadion', ['FC Köln', 'Köln']],
  ['BL1', 'Hamburger SV', 'Volksparkstadion', 'Hamburg', 'de', '', ['Hamburg']],
  ['BL1', 'FC Schalke 04', 'Veltins-Arena', 'Gelsenkirchen', 'de', '', ['Schalke 04', 'Schalke']],
  ['BL1', 'SC Paderborn 07', 'Home Deluxe Arena', 'Paderborn', 'de', '', ['Paderborn']],
  ['BL1', 'SV 07 Elversberg', 'Ursapharm-Arena an der Kaiserlinde', 'Spiesen-Elversberg', 'de', 'Ursapharm-Arena', ['SV Elversberg', 'Elversberg']],

  // ---------- Premier League ----------
  ['PL', 'Arsenal FC', 'Emirates Stadium', 'London', 'gb', '', ['FC Arsenal', 'Arsenal']],
  ['PL', 'Aston Villa FC', 'Villa Park', 'Birmingham', 'gb', '', ['Aston Villa']],
  ['PL', 'AFC Bournemouth', 'Vitality Stadium', 'Bournemouth', 'gb', 'Dean Court', ['Bournemouth']],
  ['PL', 'Brentford FC', 'Gtech Community Stadium', 'London', 'gb', 'Gtech Community Stadium', ['Brentford F.C.', 'Brentford']],
  ['PL', 'Brighton & Hove Albion FC', 'American Express Stadium', 'Brighton', 'gb', 'Falmer Stadium', ['Brighton & Hove Albion', 'Brighton']],
  ['PL', 'Chelsea FC', 'Stamford Bridge', 'London', 'gb', '', ['Chelsea']],
  ['PL', 'Coventry City FC', 'Coventry Building Society Arena', 'Coventry', 'gb', '', ['Coventry City', 'Coventry']],
  ['PL', 'Crystal Palace FC', 'Selhurst Park', 'London', 'gb', '', ['Crystal Palace']],
  ['PL', 'Everton FC', 'Hill Dickinson Stadium', 'Liverpool', 'gb', 'Hill Dickinson Stadium', ['Everton']],
  ['PL', 'Fulham FC', 'Craven Cottage', 'London', 'gb', '', ['Fulham']],
  ['PL', 'Hull City AFC', 'MKM Stadium', 'Kingston upon Hull', 'gb', '', ['Hull City', 'Hull']],
  ['PL', 'Ipswich Town FC', 'Portman Road', 'Ipswich', 'gb', 'Portman Road Stadium', ['Ipswich Town', 'Ipswich']],
  ['PL', 'Leeds United FC', 'Elland Road', 'Leeds', 'gb', 'Elland Road Stadium', ['Leeds United', 'Leeds']],
  ['PL', 'Liverpool FC', 'Anfield', 'Liverpool', 'gb', 'Anfield Stadium', ['FC Liverpool', 'Liverpool']],
  ['PL', 'Manchester City FC', 'Etihad Stadium', 'Manchester', 'gb', '', ['Manchester City', 'Man City']],
  ['PL', 'Manchester United FC', 'Old Trafford', 'Manchester', 'gb', 'Old Trafford Stadium', ['Manchester United', 'Man United']],
  ['PL', 'Newcastle United FC', "St James' Park", 'Newcastle upon Tyne', 'gb', '', ['Newcastle United', 'Newcastle']],
  ['PL', 'Nottingham Forest FC', 'City Ground', 'Nottingham', 'gb', 'City Ground, West Bridgford', ['Nottingham Forest', "Nott'm Forest"]],
  ['PL', 'Sunderland AFC', 'Stadium of Light', 'Sunderland', 'gb', '', ['Sunderland']],
  ['PL', 'Tottenham Hotspur FC', 'Tottenham Hotspur Stadium', 'London', 'gb', '', ['Tottenham Hotspur', 'Tottenham']],

  // ---------- La Liga ----------
  ['PD', 'Real Madrid CF', 'Santiago Bernabéu', 'Madrid', 'es', 'Estadio Santiago Bernabéu', ['Real Madrid']],
  ['PD', 'FC Barcelona', 'Spotify Camp Nou', 'Barcelona', 'es', 'Camp Nou', ['Barcelona']],
  ['PD', 'Club Atlético de Madrid', 'Riyadh Air Metropolitano', 'Madrid', 'es', 'Estadio Metropolitano', ['Atlético Madrid', 'Atletico Madrid', 'Ath Madrid']],
  ['PD', 'Athletic Club', 'San Mamés', 'Bilbao', 'es', 'Estadio San Mamés', ['Athletic Bilbao', 'Ath Bilbao']],
  ['PD', 'Real Sociedad de Fútbol', 'Reale Arena', 'Donostia / San Sebastián', 'es', 'Anoeta', ['Real Sociedad', 'Sociedad']],
  ['PD', 'Real Betis Balompié', 'Estadio de La Cartuja', 'Sevilla', 'es', 'Estadio de La Cartuja', ['Real Betis', 'Betis']],
  ['PD', 'Sevilla FC', 'Ramón Sánchez-Pizjuán', 'Sevilla', 'es', 'Estadio Ramón Sánchez-Pizjuán', ['FC Sevilla', 'Sevilla']],
  ['PD', 'Valencia CF', 'Mestalla', 'Valencia', 'es', 'Mestalla', ['FC Valencia', 'Valencia']],
  ['PD', 'Villarreal CF', 'Estadio de la Cerámica', 'Vila-real', 'es', 'Estadio de la Cerámica', ['FC Villareal', 'Villarreal']],
  ['PD', 'CA Osasuna', 'El Sadar', 'Pamplona', 'es', 'Estadio El Sadar', ['Osasuna']],
  ['PD', 'RC Celta de Vigo', 'Abanca-Balaídos', 'Vigo', 'es', 'Estadio de Balaídos', ['Celta Vigo', 'Celta']],
  ['PD', 'RC Deportivo La Coruña', 'Abanca-Riazor', 'A Coruña', 'es', 'Estadio de Riazor', ['Deportivo A Coruña', 'Deportivo La Coruna', 'La Coruna']],
  ['PD', 'Deportivo Alavés', 'Mendizorrotza', 'Vitoria-Gasteiz', 'es', 'Estadio de Mendizorrotza', ['Deportivo Alaves', 'Alaves']],
  ['PD', 'Elche CF', 'Martínez Valero', 'Elche', 'es', 'Estadio Manuel Martínez Valero', ['Elche']],
  ['PD', 'RCD Espanyol de Barcelona', 'RCDE Stadium', 'Cornellà de Llobregat', 'es', 'RCDE Stadium', ['Espanyol Barcelona', 'Espanyol', 'Espanol']],
  ['PD', 'Getafe CF', 'Coliseum', 'Getafe', 'es', 'Coliseum Alfonso Pérez', ['FC Getafe', 'Getafe']],
  ['PD', 'Málaga CF', 'La Rosaleda', 'Málaga', 'es', 'Estadio La Rosaleda', ['FC Malaga', 'Malaga']],
  ['PD', 'Levante UD', 'Ciutat de València', 'Valencia', 'es', 'Estadi Ciutat de València', ['Levante']],
  ['PD', 'Real Racing Club de Santander', 'El Sardinero', 'Santander', 'es', 'Campos de Sport de El Sardinero', ['Racing Santander', 'Santander']],
  ['PD', 'Rayo Vallecano de Madrid', 'Estadio de Vallecas', 'Madrid', 'es', 'Estadio de Vallecas', ['Rayo Vallecano', 'Vallecano']],

  // ---------- Serie A ----------
  ['SA', 'FC Internazionale Milano', 'San Siro', 'Milano', 'it', 'Stadio Giuseppe Meazza', ['Inter Mailand', 'Inter Milan', 'Inter']],
  ['SA', 'AC Milan', 'San Siro', 'Milano', 'it', 'Stadio Giuseppe Meazza', ['AC Mailand', 'Milan']],
  ['SA', 'Juventus FC', 'Allianz Stadium', 'Torino', 'it', 'Allianz Stadium', ['Juventus Turin', 'Juventus']],
  ['SA', 'SSC Napoli', 'Stadio Diego Armando Maradona', 'Napoli', 'it', '', ['SSC Neapel', 'Napoli']],
  ['SA', 'AS Roma', 'Stadio Olimpico', 'Roma', 'it', 'Stadio Olimpico', ['AS Rom', 'Roma']],
  ['SA', 'SS Lazio', 'Stadio Olimpico', 'Roma', 'it', 'Stadio Olimpico', ['Lazio Rom', 'Lazio']],
  ['SA', 'Atalanta BC', 'Gewiss Stadium', 'Bergamo', 'it', 'Stadio di Bergamo', ['Atalanta Bergamo', 'Atalanta']],
  ['SA', 'ACF Fiorentina', 'Stadio Artemio Franchi', 'Firenze', 'it', '', ['AC Florenz', 'Fiorentina']],
  ['SA', 'Bologna FC 1909', "Stadio Renato Dall'Ara", 'Bologna', 'it', '', ['FC Bologna', 'Bologna']],
  ['SA', 'Torino FC', 'Stadio Olimpico Grande Torino', 'Torino', 'it', '', ['FC Turin', 'Torino']],
  ['SA', 'Udinese Calcio', 'Bluenergy Stadium', 'Udine', 'it', 'Stadio Friuli', ['Udinese']],
  ['SA', 'Genoa CFC', 'Stadio Luigi Ferraris', 'Genova', 'it', '', ['CFC Genua', 'Genoa']],
  ['SA', 'Cagliari Calcio', 'Unipol Domus', 'Cagliari', 'it', '', ['Cagliari']],
  ['SA', 'US Lecce', 'Stadio Via del Mare', 'Lecce', 'it', '', ['Lecce']],
  ['SA', 'Como 1907', 'Stadio Giuseppe Sinigaglia', 'Como', 'it', '', ['Como']],
  ['SA', 'Parma Calcio 1913', 'Stadio Ennio Tardini', 'Parma', 'it', '', ['Parma']],
  ['SA', 'US Sassuolo Calcio', 'Mapei Stadium – Città del Tricolore', 'Reggio Emilia', 'it', 'Mapei Stadium', ['Sassuolo']],
  ['SA', 'AC Monza', 'U-Power Stadium', 'Monza', 'it', 'Stadio Brianteo', ['Monza']],
  ['SA', 'Venezia FC', 'Stadio Pier Luigi Penzo', 'Venezia', 'it', '', ['Venedig', 'Venezia']],
  ['SA', 'Frosinone Calcio', 'Stadio Benito Stirpe', 'Frosinone', 'it', '', ['Frosinone']],

  // ---------- Ligue 1 ----------
  ['FL1', 'Paris Saint-Germain FC', 'Parc des Princes', 'Paris', 'fr', '', ['Paris SG', 'PSG', 'Paris Saint-Germain']],
  ['FL1', 'Paris FC', 'Stade Jean-Bouin', 'Paris', 'fr', '', ['Paris FC']],
  ['FL1', 'Olympique de Marseille', 'Orange Vélodrome', 'Marseille', 'fr', 'Stade Vélodrome', ['Marseille', 'Olympique Marseille']],
  ['FL1', 'Olympique Lyonnais', 'Groupama Stadium', 'Décines-Charpieu', 'fr', 'Parc Olympique Lyonnais', ['Lyon', 'Olympique Lyon']],
  ['FL1', 'AS Monaco FC', 'Stade Louis II', 'Monaco', 'mc', 'Stade Louis II', ['Monaco', 'AS Monaco']],
  ['FL1', 'LOSC Lille', 'Decathlon Arena – Stade Pierre-Mauroy', "Villeneuve-d'Ascq", 'fr', 'Stade Pierre-Mauroy', ['Lille', 'OSC Lille']],
  ['FL1', 'RC Lens', 'Stade Bollaert-Delelis', 'Lens', 'fr', '', ['Lens']],
  ['FL1', 'OGC Nice', 'Allianz Riviera', 'Nice', 'fr', '', ['Nice', 'OGC Nizza']],
  ['FL1', 'Stade Rennais FC 1901', 'Roazhon Park', 'Rennes', 'fr', '', ['Rennes', 'Stade Rennes']],
  ['FL1', 'RC Strasbourg Alsace', 'Stade de la Meinau', 'Strasbourg', 'fr', '', ['Strasbourg', 'Racing Straßburg']],
  ['FL1', 'Toulouse FC', 'Stadium de Toulouse', 'Toulouse', 'fr', '', ['Toulouse']],
  ['FL1', 'Stade Brestois 29', 'Stade Francis-Le Blé', 'Brest', 'fr', '', ['Brest', 'Stade Brest']],
  ['FL1', 'AJ Auxerre', "Stade de l'Abbé-Deschamps", 'Auxerre', 'fr', 'Stade Abbé-Deschamps', ['Auxerre']],
  ['FL1', 'Angers SCO', 'Stade Raymond-Kopa', 'Angers', 'fr', '', ['Angers']],
  ['FL1', 'Le Havre AC', 'Stade Océane', 'Le Havre', 'fr', '', ['Le Havre']],
  ['FL1', 'Le Mans FC', 'MMArena', 'Le Mans', 'fr', 'MMArena', ['Le Mans']],
  ['FL1', 'FC Lorient', 'Stade du Moustoir', 'Lorient', 'fr', '', ['Lorient']],
  ['FL1', 'ES Troyes AC', "Stade de l'Aube", 'Troyes', 'fr', '', ['Troyes']],
]
